apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: default
  labels:
    app: authservice
  annotations:
    argocd.argoproj.io/tracking-id: authservice:apps/Deployment:default/authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      serviceAccountName: authservice

      containers:
        - name: server
          image: manoj99eng/authservice:e346ac7840540422e8cd4d716f44cb68e5848565
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: PORT
              value: "8081"

          envFrom:
            - secretRef:
                name: authservice-secret

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: authservice-secrets

      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
